# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    docker-compose.yml                                 :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: mayoub <mayoub@student.42nice.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#                                                      #+#    #+#              #
#                                                     ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

version: '3'

service:

  nginx:
    build:
      context: .
      dockerfile: requirement/nginx/Dockerfile
    container_name: nginx
  depends_on:
   - wordpress
  ports:
    - "443:443"
  networks:
    - inception
  volumes:
    - ./requirement/nginx/conf/:/etc/nginx/http.d/
    - ./requirement/nginx/tools/:/etc/nginx/ssl/
  restart: always

  mariadb:
    build:
      context: .
      dockerfile: mariadb/Dockerfile
      args:
        DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_ROOT: ${DB_ROOT}
    container_name: mariadb
    ports:
      - "3306:3306"
    networks:
    - inception
    restart: always

  wordpress:
    build:
      context: .
      dockerfile: wordpress/Dockerfile
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
    container_name: wordpress
    depends_on:
      - mariadb
    networks:
    - inception
    restart: always
    volumes:
      - wp-volume:/var/www/

volumes:

  wp-volume:
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/wordpress

    db-volume:
      driver_opts:
        o: bind
        type: none
        device: /home/${USER}/data/mariadb

networks:
  inception:
    drivers: bridge
